### ISSUE TITLE
requirements.txt file not added

### ISSUE THREAD

**Issue by ashu9999** [DebanjanaKar/Covid19_FakeNews_Detection#2]
Please add the  requirements.txt file in the repo. Thank you.

**Comment by DebanjanaKar** [comment]
The environment.yml or requirements.txt file is there in each task folder. The steps to install are also mentioned. Kindly follow the same. If you face any more problems finding these files, let me know.

**Comment by ashu9999** [comment]
I want to setup the flask app on my local machine for the multilingual model, but i am getting errors. I did not find any requirements file in the GUI-ML-Models folder. Please help to setup the app.

**Comment by ashu9999** [comment]
@DebanjanaKar Mam please give me steps for setting the multilingual Flask app on my local host.

**Comment by ashu9999** [comment]
Also i am not able to access the pretrained model.

**Comment by DebanjanaKar** [comment]
Hi @ashu9999 ! Sorry for not being able to reply in the past few days. Thanks for pointing it out, I have added the requirements file in the GUI-ML folder. I have also changed the link to the pre-trained model. In case you are still facing a problem, let me know.

**Comment by ashu9999** [comment]
I am running the english flask app after creating a venv and installing all the req. 
When i am entering any new tweet URL or only the ID , everytime it is downloading (400 MB) something (see the screenshot bottom bars). I can't figure out whats happening. 
I thought it would output something like verified or not. What do you say??_
![server](https://user-images.githubusercontent.com/36306781/97352637-ea5dd880-18b8-11eb-9bd4-0a78239eabe1.png)
_

**Comment by mohit19014** [comment]
Hi Ashu, the file that is being downloaded again and again in your case is Sentence BERT model (405 MB), to get the 768 dimension vector embedding of the tweet text. 

I am not sure about Linux but this doesn't happen in Windows as once the Sentence BERT model has been downloaded, it always picks up the already downloaded model.
